truncate table Seat;
insert into Seat(id,student) values('1','Abbot');
insert into Seat(id,student) values('2','Doris');
insert into Seat(id,student) values('3','Emerson');
insert into Seat(id,student) values('4','Green');
insert into Seat(id,student) values('5','Jeames');
truncate table Expected;
insert into Expected(id,student) values('1','Doris');
insert into Expected(id,student) values('2','Abbot');
insert into Expected(id,student) values('3','Green');
insert into Expected(id,student) values('4','Emerson');
insert into Expected(id,student) values('5','Jeames');
